// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/px.proto

package com.katalon.kit.px;

/**
 * Protobuf type {@code px.Action}
 */
public  final class Action extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:px.Action)
    ActionOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Action.newBuilder() to construct.
  private Action(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Action() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Action();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Action(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.katalon.kit.px.LaunchAction.Builder subBuilder = null;
            if (actionOneofCase_ == 1) {
              subBuilder = ((com.katalon.kit.px.LaunchAction) actionOneof_).toBuilder();
            }
            actionOneof_ =
                input.readMessage(com.katalon.kit.px.LaunchAction.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((com.katalon.kit.px.LaunchAction) actionOneof_);
              actionOneof_ = subBuilder.buildPartial();
            }
            actionOneofCase_ = 1;
            break;
          }
          case 18: {
            com.katalon.kit.px.GotoAction.Builder subBuilder = null;
            if (actionOneofCase_ == 2) {
              subBuilder = ((com.katalon.kit.px.GotoAction) actionOneof_).toBuilder();
            }
            actionOneof_ =
                input.readMessage(com.katalon.kit.px.GotoAction.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((com.katalon.kit.px.GotoAction) actionOneof_);
              actionOneof_ = subBuilder.buildPartial();
            }
            actionOneofCase_ = 2;
            break;
          }
          case 26: {
            com.katalon.kit.px.ClickAction.Builder subBuilder = null;
            if (actionOneofCase_ == 3) {
              subBuilder = ((com.katalon.kit.px.ClickAction) actionOneof_).toBuilder();
            }
            actionOneof_ =
                input.readMessage(com.katalon.kit.px.ClickAction.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((com.katalon.kit.px.ClickAction) actionOneof_);
              actionOneof_ = subBuilder.buildPartial();
            }
            actionOneofCase_ = 3;
            break;
          }
          case 34: {
            com.katalon.kit.px.TypeAction.Builder subBuilder = null;
            if (actionOneofCase_ == 4) {
              subBuilder = ((com.katalon.kit.px.TypeAction) actionOneof_).toBuilder();
            }
            actionOneof_ =
                input.readMessage(com.katalon.kit.px.TypeAction.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((com.katalon.kit.px.TypeAction) actionOneof_);
              actionOneof_ = subBuilder.buildPartial();
            }
            actionOneofCase_ = 4;
            break;
          }
          case 42: {
            com.katalon.kit.px.SelectAction.Builder subBuilder = null;
            if (actionOneofCase_ == 5) {
              subBuilder = ((com.katalon.kit.px.SelectAction) actionOneof_).toBuilder();
            }
            actionOneof_ =
                input.readMessage(com.katalon.kit.px.SelectAction.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((com.katalon.kit.px.SelectAction) actionOneof_);
              actionOneof_ = subBuilder.buildPartial();
            }
            actionOneofCase_ = 5;
            break;
          }
          case 50: {
            com.katalon.kit.px.GetInnerTextAction.Builder subBuilder = null;
            if (actionOneofCase_ == 6) {
              subBuilder = ((com.katalon.kit.px.GetInnerTextAction) actionOneof_).toBuilder();
            }
            actionOneof_ =
                input.readMessage(com.katalon.kit.px.GetInnerTextAction.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((com.katalon.kit.px.GetInnerTextAction) actionOneof_);
              actionOneof_ = subBuilder.buildPartial();
            }
            actionOneofCase_ = 6;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.katalon.kit.px.BrowserProto.internal_static_px_Action_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.katalon.kit.px.BrowserProto.internal_static_px_Action_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.katalon.kit.px.Action.class, com.katalon.kit.px.Action.Builder.class);
  }

  private int actionOneofCase_ = 0;
  private java.lang.Object actionOneof_;
  public enum ActionOneofCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    LAUNCHACTION(1),
    GOTOACTION(2),
    CLICKACTION(3),
    TYPEACTION(4),
    SELECTACTION(5),
    GETINNERTEXTACTION(6),
    ACTIONONEOF_NOT_SET(0);
    private final int value;
    private ActionOneofCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ActionOneofCase valueOf(int value) {
      return forNumber(value);
    }

    public static ActionOneofCase forNumber(int value) {
      switch (value) {
        case 1: return LAUNCHACTION;
        case 2: return GOTOACTION;
        case 3: return CLICKACTION;
        case 4: return TYPEACTION;
        case 5: return SELECTACTION;
        case 6: return GETINNERTEXTACTION;
        case 0: return ACTIONONEOF_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public ActionOneofCase
  getActionOneofCase() {
    return ActionOneofCase.forNumber(
        actionOneofCase_);
  }

  public static final int LAUNCHACTION_FIELD_NUMBER = 1;
  /**
   * <code>.px.LaunchAction launchAction = 1;</code>
   * @return Whether the launchAction field is set.
   */
  public boolean hasLaunchAction() {
    return actionOneofCase_ == 1;
  }
  /**
   * <code>.px.LaunchAction launchAction = 1;</code>
   * @return The launchAction.
   */
  public com.katalon.kit.px.LaunchAction getLaunchAction() {
    if (actionOneofCase_ == 1) {
       return (com.katalon.kit.px.LaunchAction) actionOneof_;
    }
    return com.katalon.kit.px.LaunchAction.getDefaultInstance();
  }
  /**
   * <code>.px.LaunchAction launchAction = 1;</code>
   */
  public com.katalon.kit.px.LaunchActionOrBuilder getLaunchActionOrBuilder() {
    if (actionOneofCase_ == 1) {
       return (com.katalon.kit.px.LaunchAction) actionOneof_;
    }
    return com.katalon.kit.px.LaunchAction.getDefaultInstance();
  }

  public static final int GOTOACTION_FIELD_NUMBER = 2;
  /**
   * <code>.px.GotoAction gotoAction = 2;</code>
   * @return Whether the gotoAction field is set.
   */
  public boolean hasGotoAction() {
    return actionOneofCase_ == 2;
  }
  /**
   * <code>.px.GotoAction gotoAction = 2;</code>
   * @return The gotoAction.
   */
  public com.katalon.kit.px.GotoAction getGotoAction() {
    if (actionOneofCase_ == 2) {
       return (com.katalon.kit.px.GotoAction) actionOneof_;
    }
    return com.katalon.kit.px.GotoAction.getDefaultInstance();
  }
  /**
   * <code>.px.GotoAction gotoAction = 2;</code>
   */
  public com.katalon.kit.px.GotoActionOrBuilder getGotoActionOrBuilder() {
    if (actionOneofCase_ == 2) {
       return (com.katalon.kit.px.GotoAction) actionOneof_;
    }
    return com.katalon.kit.px.GotoAction.getDefaultInstance();
  }

  public static final int CLICKACTION_FIELD_NUMBER = 3;
  /**
   * <code>.px.ClickAction clickAction = 3;</code>
   * @return Whether the clickAction field is set.
   */
  public boolean hasClickAction() {
    return actionOneofCase_ == 3;
  }
  /**
   * <code>.px.ClickAction clickAction = 3;</code>
   * @return The clickAction.
   */
  public com.katalon.kit.px.ClickAction getClickAction() {
    if (actionOneofCase_ == 3) {
       return (com.katalon.kit.px.ClickAction) actionOneof_;
    }
    return com.katalon.kit.px.ClickAction.getDefaultInstance();
  }
  /**
   * <code>.px.ClickAction clickAction = 3;</code>
   */
  public com.katalon.kit.px.ClickActionOrBuilder getClickActionOrBuilder() {
    if (actionOneofCase_ == 3) {
       return (com.katalon.kit.px.ClickAction) actionOneof_;
    }
    return com.katalon.kit.px.ClickAction.getDefaultInstance();
  }

  public static final int TYPEACTION_FIELD_NUMBER = 4;
  /**
   * <code>.px.TypeAction typeAction = 4;</code>
   * @return Whether the typeAction field is set.
   */
  public boolean hasTypeAction() {
    return actionOneofCase_ == 4;
  }
  /**
   * <code>.px.TypeAction typeAction = 4;</code>
   * @return The typeAction.
   */
  public com.katalon.kit.px.TypeAction getTypeAction() {
    if (actionOneofCase_ == 4) {
       return (com.katalon.kit.px.TypeAction) actionOneof_;
    }
    return com.katalon.kit.px.TypeAction.getDefaultInstance();
  }
  /**
   * <code>.px.TypeAction typeAction = 4;</code>
   */
  public com.katalon.kit.px.TypeActionOrBuilder getTypeActionOrBuilder() {
    if (actionOneofCase_ == 4) {
       return (com.katalon.kit.px.TypeAction) actionOneof_;
    }
    return com.katalon.kit.px.TypeAction.getDefaultInstance();
  }

  public static final int SELECTACTION_FIELD_NUMBER = 5;
  /**
   * <code>.px.SelectAction selectAction = 5;</code>
   * @return Whether the selectAction field is set.
   */
  public boolean hasSelectAction() {
    return actionOneofCase_ == 5;
  }
  /**
   * <code>.px.SelectAction selectAction = 5;</code>
   * @return The selectAction.
   */
  public com.katalon.kit.px.SelectAction getSelectAction() {
    if (actionOneofCase_ == 5) {
       return (com.katalon.kit.px.SelectAction) actionOneof_;
    }
    return com.katalon.kit.px.SelectAction.getDefaultInstance();
  }
  /**
   * <code>.px.SelectAction selectAction = 5;</code>
   */
  public com.katalon.kit.px.SelectActionOrBuilder getSelectActionOrBuilder() {
    if (actionOneofCase_ == 5) {
       return (com.katalon.kit.px.SelectAction) actionOneof_;
    }
    return com.katalon.kit.px.SelectAction.getDefaultInstance();
  }

  public static final int GETINNERTEXTACTION_FIELD_NUMBER = 6;
  /**
   * <code>.px.GetInnerTextAction getInnerTextAction = 6;</code>
   * @return Whether the getInnerTextAction field is set.
   */
  public boolean hasGetInnerTextAction() {
    return actionOneofCase_ == 6;
  }
  /**
   * <code>.px.GetInnerTextAction getInnerTextAction = 6;</code>
   * @return The getInnerTextAction.
   */
  public com.katalon.kit.px.GetInnerTextAction getGetInnerTextAction() {
    if (actionOneofCase_ == 6) {
       return (com.katalon.kit.px.GetInnerTextAction) actionOneof_;
    }
    return com.katalon.kit.px.GetInnerTextAction.getDefaultInstance();
  }
  /**
   * <code>.px.GetInnerTextAction getInnerTextAction = 6;</code>
   */
  public com.katalon.kit.px.GetInnerTextActionOrBuilder getGetInnerTextActionOrBuilder() {
    if (actionOneofCase_ == 6) {
       return (com.katalon.kit.px.GetInnerTextAction) actionOneof_;
    }
    return com.katalon.kit.px.GetInnerTextAction.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (actionOneofCase_ == 1) {
      output.writeMessage(1, (com.katalon.kit.px.LaunchAction) actionOneof_);
    }
    if (actionOneofCase_ == 2) {
      output.writeMessage(2, (com.katalon.kit.px.GotoAction) actionOneof_);
    }
    if (actionOneofCase_ == 3) {
      output.writeMessage(3, (com.katalon.kit.px.ClickAction) actionOneof_);
    }
    if (actionOneofCase_ == 4) {
      output.writeMessage(4, (com.katalon.kit.px.TypeAction) actionOneof_);
    }
    if (actionOneofCase_ == 5) {
      output.writeMessage(5, (com.katalon.kit.px.SelectAction) actionOneof_);
    }
    if (actionOneofCase_ == 6) {
      output.writeMessage(6, (com.katalon.kit.px.GetInnerTextAction) actionOneof_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (actionOneofCase_ == 1) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, (com.katalon.kit.px.LaunchAction) actionOneof_);
    }
    if (actionOneofCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (com.katalon.kit.px.GotoAction) actionOneof_);
    }
    if (actionOneofCase_ == 3) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, (com.katalon.kit.px.ClickAction) actionOneof_);
    }
    if (actionOneofCase_ == 4) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, (com.katalon.kit.px.TypeAction) actionOneof_);
    }
    if (actionOneofCase_ == 5) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, (com.katalon.kit.px.SelectAction) actionOneof_);
    }
    if (actionOneofCase_ == 6) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, (com.katalon.kit.px.GetInnerTextAction) actionOneof_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.katalon.kit.px.Action)) {
      return super.equals(obj);
    }
    com.katalon.kit.px.Action other = (com.katalon.kit.px.Action) obj;

    if (!getActionOneofCase().equals(other.getActionOneofCase())) return false;
    switch (actionOneofCase_) {
      case 1:
        if (!getLaunchAction()
            .equals(other.getLaunchAction())) return false;
        break;
      case 2:
        if (!getGotoAction()
            .equals(other.getGotoAction())) return false;
        break;
      case 3:
        if (!getClickAction()
            .equals(other.getClickAction())) return false;
        break;
      case 4:
        if (!getTypeAction()
            .equals(other.getTypeAction())) return false;
        break;
      case 5:
        if (!getSelectAction()
            .equals(other.getSelectAction())) return false;
        break;
      case 6:
        if (!getGetInnerTextAction()
            .equals(other.getGetInnerTextAction())) return false;
        break;
      case 0:
      default:
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    switch (actionOneofCase_) {
      case 1:
        hash = (37 * hash) + LAUNCHACTION_FIELD_NUMBER;
        hash = (53 * hash) + getLaunchAction().hashCode();
        break;
      case 2:
        hash = (37 * hash) + GOTOACTION_FIELD_NUMBER;
        hash = (53 * hash) + getGotoAction().hashCode();
        break;
      case 3:
        hash = (37 * hash) + CLICKACTION_FIELD_NUMBER;
        hash = (53 * hash) + getClickAction().hashCode();
        break;
      case 4:
        hash = (37 * hash) + TYPEACTION_FIELD_NUMBER;
        hash = (53 * hash) + getTypeAction().hashCode();
        break;
      case 5:
        hash = (37 * hash) + SELECTACTION_FIELD_NUMBER;
        hash = (53 * hash) + getSelectAction().hashCode();
        break;
      case 6:
        hash = (37 * hash) + GETINNERTEXTACTION_FIELD_NUMBER;
        hash = (53 * hash) + getGetInnerTextAction().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.katalon.kit.px.Action parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.katalon.kit.px.Action parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.katalon.kit.px.Action parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.katalon.kit.px.Action parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.katalon.kit.px.Action parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.katalon.kit.px.Action parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.katalon.kit.px.Action parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.katalon.kit.px.Action parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.katalon.kit.px.Action parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.katalon.kit.px.Action parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.katalon.kit.px.Action parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.katalon.kit.px.Action parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.katalon.kit.px.Action prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code px.Action}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:px.Action)
      com.katalon.kit.px.ActionOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.katalon.kit.px.BrowserProto.internal_static_px_Action_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.katalon.kit.px.BrowserProto.internal_static_px_Action_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.katalon.kit.px.Action.class, com.katalon.kit.px.Action.Builder.class);
    }

    // Construct using com.katalon.kit.px.Action.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      actionOneofCase_ = 0;
      actionOneof_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.katalon.kit.px.BrowserProto.internal_static_px_Action_descriptor;
    }

    @java.lang.Override
    public com.katalon.kit.px.Action getDefaultInstanceForType() {
      return com.katalon.kit.px.Action.getDefaultInstance();
    }

    @java.lang.Override
    public com.katalon.kit.px.Action build() {
      com.katalon.kit.px.Action result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.katalon.kit.px.Action buildPartial() {
      com.katalon.kit.px.Action result = new com.katalon.kit.px.Action(this);
      if (actionOneofCase_ == 1) {
        if (launchActionBuilder_ == null) {
          result.actionOneof_ = actionOneof_;
        } else {
          result.actionOneof_ = launchActionBuilder_.build();
        }
      }
      if (actionOneofCase_ == 2) {
        if (gotoActionBuilder_ == null) {
          result.actionOneof_ = actionOneof_;
        } else {
          result.actionOneof_ = gotoActionBuilder_.build();
        }
      }
      if (actionOneofCase_ == 3) {
        if (clickActionBuilder_ == null) {
          result.actionOneof_ = actionOneof_;
        } else {
          result.actionOneof_ = clickActionBuilder_.build();
        }
      }
      if (actionOneofCase_ == 4) {
        if (typeActionBuilder_ == null) {
          result.actionOneof_ = actionOneof_;
        } else {
          result.actionOneof_ = typeActionBuilder_.build();
        }
      }
      if (actionOneofCase_ == 5) {
        if (selectActionBuilder_ == null) {
          result.actionOneof_ = actionOneof_;
        } else {
          result.actionOneof_ = selectActionBuilder_.build();
        }
      }
      if (actionOneofCase_ == 6) {
        if (getInnerTextActionBuilder_ == null) {
          result.actionOneof_ = actionOneof_;
        } else {
          result.actionOneof_ = getInnerTextActionBuilder_.build();
        }
      }
      result.actionOneofCase_ = actionOneofCase_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.katalon.kit.px.Action) {
        return mergeFrom((com.katalon.kit.px.Action)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.katalon.kit.px.Action other) {
      if (other == com.katalon.kit.px.Action.getDefaultInstance()) return this;
      switch (other.getActionOneofCase()) {
        case LAUNCHACTION: {
          mergeLaunchAction(other.getLaunchAction());
          break;
        }
        case GOTOACTION: {
          mergeGotoAction(other.getGotoAction());
          break;
        }
        case CLICKACTION: {
          mergeClickAction(other.getClickAction());
          break;
        }
        case TYPEACTION: {
          mergeTypeAction(other.getTypeAction());
          break;
        }
        case SELECTACTION: {
          mergeSelectAction(other.getSelectAction());
          break;
        }
        case GETINNERTEXTACTION: {
          mergeGetInnerTextAction(other.getGetInnerTextAction());
          break;
        }
        case ACTIONONEOF_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.katalon.kit.px.Action parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.katalon.kit.px.Action) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int actionOneofCase_ = 0;
    private java.lang.Object actionOneof_;
    public ActionOneofCase
        getActionOneofCase() {
      return ActionOneofCase.forNumber(
          actionOneofCase_);
    }

    public Builder clearActionOneof() {
      actionOneofCase_ = 0;
      actionOneof_ = null;
      onChanged();
      return this;
    }


    private com.google.protobuf.SingleFieldBuilderV3<
        com.katalon.kit.px.LaunchAction, com.katalon.kit.px.LaunchAction.Builder, com.katalon.kit.px.LaunchActionOrBuilder> launchActionBuilder_;
    /**
     * <code>.px.LaunchAction launchAction = 1;</code>
     * @return Whether the launchAction field is set.
     */
    public boolean hasLaunchAction() {
      return actionOneofCase_ == 1;
    }
    /**
     * <code>.px.LaunchAction launchAction = 1;</code>
     * @return The launchAction.
     */
    public com.katalon.kit.px.LaunchAction getLaunchAction() {
      if (launchActionBuilder_ == null) {
        if (actionOneofCase_ == 1) {
          return (com.katalon.kit.px.LaunchAction) actionOneof_;
        }
        return com.katalon.kit.px.LaunchAction.getDefaultInstance();
      } else {
        if (actionOneofCase_ == 1) {
          return launchActionBuilder_.getMessage();
        }
        return com.katalon.kit.px.LaunchAction.getDefaultInstance();
      }
    }
    /**
     * <code>.px.LaunchAction launchAction = 1;</code>
     */
    public Builder setLaunchAction(com.katalon.kit.px.LaunchAction value) {
      if (launchActionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        actionOneof_ = value;
        onChanged();
      } else {
        launchActionBuilder_.setMessage(value);
      }
      actionOneofCase_ = 1;
      return this;
    }
    /**
     * <code>.px.LaunchAction launchAction = 1;</code>
     */
    public Builder setLaunchAction(
        com.katalon.kit.px.LaunchAction.Builder builderForValue) {
      if (launchActionBuilder_ == null) {
        actionOneof_ = builderForValue.build();
        onChanged();
      } else {
        launchActionBuilder_.setMessage(builderForValue.build());
      }
      actionOneofCase_ = 1;
      return this;
    }
    /**
     * <code>.px.LaunchAction launchAction = 1;</code>
     */
    public Builder mergeLaunchAction(com.katalon.kit.px.LaunchAction value) {
      if (launchActionBuilder_ == null) {
        if (actionOneofCase_ == 1 &&
            actionOneof_ != com.katalon.kit.px.LaunchAction.getDefaultInstance()) {
          actionOneof_ = com.katalon.kit.px.LaunchAction.newBuilder((com.katalon.kit.px.LaunchAction) actionOneof_)
              .mergeFrom(value).buildPartial();
        } else {
          actionOneof_ = value;
        }
        onChanged();
      } else {
        if (actionOneofCase_ == 1) {
          launchActionBuilder_.mergeFrom(value);
        }
        launchActionBuilder_.setMessage(value);
      }
      actionOneofCase_ = 1;
      return this;
    }
    /**
     * <code>.px.LaunchAction launchAction = 1;</code>
     */
    public Builder clearLaunchAction() {
      if (launchActionBuilder_ == null) {
        if (actionOneofCase_ == 1) {
          actionOneofCase_ = 0;
          actionOneof_ = null;
          onChanged();
        }
      } else {
        if (actionOneofCase_ == 1) {
          actionOneofCase_ = 0;
          actionOneof_ = null;
        }
        launchActionBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.px.LaunchAction launchAction = 1;</code>
     */
    public com.katalon.kit.px.LaunchAction.Builder getLaunchActionBuilder() {
      return getLaunchActionFieldBuilder().getBuilder();
    }
    /**
     * <code>.px.LaunchAction launchAction = 1;</code>
     */
    public com.katalon.kit.px.LaunchActionOrBuilder getLaunchActionOrBuilder() {
      if ((actionOneofCase_ == 1) && (launchActionBuilder_ != null)) {
        return launchActionBuilder_.getMessageOrBuilder();
      } else {
        if (actionOneofCase_ == 1) {
          return (com.katalon.kit.px.LaunchAction) actionOneof_;
        }
        return com.katalon.kit.px.LaunchAction.getDefaultInstance();
      }
    }
    /**
     * <code>.px.LaunchAction launchAction = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.katalon.kit.px.LaunchAction, com.katalon.kit.px.LaunchAction.Builder, com.katalon.kit.px.LaunchActionOrBuilder> 
        getLaunchActionFieldBuilder() {
      if (launchActionBuilder_ == null) {
        if (!(actionOneofCase_ == 1)) {
          actionOneof_ = com.katalon.kit.px.LaunchAction.getDefaultInstance();
        }
        launchActionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.katalon.kit.px.LaunchAction, com.katalon.kit.px.LaunchAction.Builder, com.katalon.kit.px.LaunchActionOrBuilder>(
                (com.katalon.kit.px.LaunchAction) actionOneof_,
                getParentForChildren(),
                isClean());
        actionOneof_ = null;
      }
      actionOneofCase_ = 1;
      onChanged();;
      return launchActionBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.katalon.kit.px.GotoAction, com.katalon.kit.px.GotoAction.Builder, com.katalon.kit.px.GotoActionOrBuilder> gotoActionBuilder_;
    /**
     * <code>.px.GotoAction gotoAction = 2;</code>
     * @return Whether the gotoAction field is set.
     */
    public boolean hasGotoAction() {
      return actionOneofCase_ == 2;
    }
    /**
     * <code>.px.GotoAction gotoAction = 2;</code>
     * @return The gotoAction.
     */
    public com.katalon.kit.px.GotoAction getGotoAction() {
      if (gotoActionBuilder_ == null) {
        if (actionOneofCase_ == 2) {
          return (com.katalon.kit.px.GotoAction) actionOneof_;
        }
        return com.katalon.kit.px.GotoAction.getDefaultInstance();
      } else {
        if (actionOneofCase_ == 2) {
          return gotoActionBuilder_.getMessage();
        }
        return com.katalon.kit.px.GotoAction.getDefaultInstance();
      }
    }
    /**
     * <code>.px.GotoAction gotoAction = 2;</code>
     */
    public Builder setGotoAction(com.katalon.kit.px.GotoAction value) {
      if (gotoActionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        actionOneof_ = value;
        onChanged();
      } else {
        gotoActionBuilder_.setMessage(value);
      }
      actionOneofCase_ = 2;
      return this;
    }
    /**
     * <code>.px.GotoAction gotoAction = 2;</code>
     */
    public Builder setGotoAction(
        com.katalon.kit.px.GotoAction.Builder builderForValue) {
      if (gotoActionBuilder_ == null) {
        actionOneof_ = builderForValue.build();
        onChanged();
      } else {
        gotoActionBuilder_.setMessage(builderForValue.build());
      }
      actionOneofCase_ = 2;
      return this;
    }
    /**
     * <code>.px.GotoAction gotoAction = 2;</code>
     */
    public Builder mergeGotoAction(com.katalon.kit.px.GotoAction value) {
      if (gotoActionBuilder_ == null) {
        if (actionOneofCase_ == 2 &&
            actionOneof_ != com.katalon.kit.px.GotoAction.getDefaultInstance()) {
          actionOneof_ = com.katalon.kit.px.GotoAction.newBuilder((com.katalon.kit.px.GotoAction) actionOneof_)
              .mergeFrom(value).buildPartial();
        } else {
          actionOneof_ = value;
        }
        onChanged();
      } else {
        if (actionOneofCase_ == 2) {
          gotoActionBuilder_.mergeFrom(value);
        }
        gotoActionBuilder_.setMessage(value);
      }
      actionOneofCase_ = 2;
      return this;
    }
    /**
     * <code>.px.GotoAction gotoAction = 2;</code>
     */
    public Builder clearGotoAction() {
      if (gotoActionBuilder_ == null) {
        if (actionOneofCase_ == 2) {
          actionOneofCase_ = 0;
          actionOneof_ = null;
          onChanged();
        }
      } else {
        if (actionOneofCase_ == 2) {
          actionOneofCase_ = 0;
          actionOneof_ = null;
        }
        gotoActionBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.px.GotoAction gotoAction = 2;</code>
     */
    public com.katalon.kit.px.GotoAction.Builder getGotoActionBuilder() {
      return getGotoActionFieldBuilder().getBuilder();
    }
    /**
     * <code>.px.GotoAction gotoAction = 2;</code>
     */
    public com.katalon.kit.px.GotoActionOrBuilder getGotoActionOrBuilder() {
      if ((actionOneofCase_ == 2) && (gotoActionBuilder_ != null)) {
        return gotoActionBuilder_.getMessageOrBuilder();
      } else {
        if (actionOneofCase_ == 2) {
          return (com.katalon.kit.px.GotoAction) actionOneof_;
        }
        return com.katalon.kit.px.GotoAction.getDefaultInstance();
      }
    }
    /**
     * <code>.px.GotoAction gotoAction = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.katalon.kit.px.GotoAction, com.katalon.kit.px.GotoAction.Builder, com.katalon.kit.px.GotoActionOrBuilder> 
        getGotoActionFieldBuilder() {
      if (gotoActionBuilder_ == null) {
        if (!(actionOneofCase_ == 2)) {
          actionOneof_ = com.katalon.kit.px.GotoAction.getDefaultInstance();
        }
        gotoActionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.katalon.kit.px.GotoAction, com.katalon.kit.px.GotoAction.Builder, com.katalon.kit.px.GotoActionOrBuilder>(
                (com.katalon.kit.px.GotoAction) actionOneof_,
                getParentForChildren(),
                isClean());
        actionOneof_ = null;
      }
      actionOneofCase_ = 2;
      onChanged();;
      return gotoActionBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.katalon.kit.px.ClickAction, com.katalon.kit.px.ClickAction.Builder, com.katalon.kit.px.ClickActionOrBuilder> clickActionBuilder_;
    /**
     * <code>.px.ClickAction clickAction = 3;</code>
     * @return Whether the clickAction field is set.
     */
    public boolean hasClickAction() {
      return actionOneofCase_ == 3;
    }
    /**
     * <code>.px.ClickAction clickAction = 3;</code>
     * @return The clickAction.
     */
    public com.katalon.kit.px.ClickAction getClickAction() {
      if (clickActionBuilder_ == null) {
        if (actionOneofCase_ == 3) {
          return (com.katalon.kit.px.ClickAction) actionOneof_;
        }
        return com.katalon.kit.px.ClickAction.getDefaultInstance();
      } else {
        if (actionOneofCase_ == 3) {
          return clickActionBuilder_.getMessage();
        }
        return com.katalon.kit.px.ClickAction.getDefaultInstance();
      }
    }
    /**
     * <code>.px.ClickAction clickAction = 3;</code>
     */
    public Builder setClickAction(com.katalon.kit.px.ClickAction value) {
      if (clickActionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        actionOneof_ = value;
        onChanged();
      } else {
        clickActionBuilder_.setMessage(value);
      }
      actionOneofCase_ = 3;
      return this;
    }
    /**
     * <code>.px.ClickAction clickAction = 3;</code>
     */
    public Builder setClickAction(
        com.katalon.kit.px.ClickAction.Builder builderForValue) {
      if (clickActionBuilder_ == null) {
        actionOneof_ = builderForValue.build();
        onChanged();
      } else {
        clickActionBuilder_.setMessage(builderForValue.build());
      }
      actionOneofCase_ = 3;
      return this;
    }
    /**
     * <code>.px.ClickAction clickAction = 3;</code>
     */
    public Builder mergeClickAction(com.katalon.kit.px.ClickAction value) {
      if (clickActionBuilder_ == null) {
        if (actionOneofCase_ == 3 &&
            actionOneof_ != com.katalon.kit.px.ClickAction.getDefaultInstance()) {
          actionOneof_ = com.katalon.kit.px.ClickAction.newBuilder((com.katalon.kit.px.ClickAction) actionOneof_)
              .mergeFrom(value).buildPartial();
        } else {
          actionOneof_ = value;
        }
        onChanged();
      } else {
        if (actionOneofCase_ == 3) {
          clickActionBuilder_.mergeFrom(value);
        }
        clickActionBuilder_.setMessage(value);
      }
      actionOneofCase_ = 3;
      return this;
    }
    /**
     * <code>.px.ClickAction clickAction = 3;</code>
     */
    public Builder clearClickAction() {
      if (clickActionBuilder_ == null) {
        if (actionOneofCase_ == 3) {
          actionOneofCase_ = 0;
          actionOneof_ = null;
          onChanged();
        }
      } else {
        if (actionOneofCase_ == 3) {
          actionOneofCase_ = 0;
          actionOneof_ = null;
        }
        clickActionBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.px.ClickAction clickAction = 3;</code>
     */
    public com.katalon.kit.px.ClickAction.Builder getClickActionBuilder() {
      return getClickActionFieldBuilder().getBuilder();
    }
    /**
     * <code>.px.ClickAction clickAction = 3;</code>
     */
    public com.katalon.kit.px.ClickActionOrBuilder getClickActionOrBuilder() {
      if ((actionOneofCase_ == 3) && (clickActionBuilder_ != null)) {
        return clickActionBuilder_.getMessageOrBuilder();
      } else {
        if (actionOneofCase_ == 3) {
          return (com.katalon.kit.px.ClickAction) actionOneof_;
        }
        return com.katalon.kit.px.ClickAction.getDefaultInstance();
      }
    }
    /**
     * <code>.px.ClickAction clickAction = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.katalon.kit.px.ClickAction, com.katalon.kit.px.ClickAction.Builder, com.katalon.kit.px.ClickActionOrBuilder> 
        getClickActionFieldBuilder() {
      if (clickActionBuilder_ == null) {
        if (!(actionOneofCase_ == 3)) {
          actionOneof_ = com.katalon.kit.px.ClickAction.getDefaultInstance();
        }
        clickActionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.katalon.kit.px.ClickAction, com.katalon.kit.px.ClickAction.Builder, com.katalon.kit.px.ClickActionOrBuilder>(
                (com.katalon.kit.px.ClickAction) actionOneof_,
                getParentForChildren(),
                isClean());
        actionOneof_ = null;
      }
      actionOneofCase_ = 3;
      onChanged();;
      return clickActionBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.katalon.kit.px.TypeAction, com.katalon.kit.px.TypeAction.Builder, com.katalon.kit.px.TypeActionOrBuilder> typeActionBuilder_;
    /**
     * <code>.px.TypeAction typeAction = 4;</code>
     * @return Whether the typeAction field is set.
     */
    public boolean hasTypeAction() {
      return actionOneofCase_ == 4;
    }
    /**
     * <code>.px.TypeAction typeAction = 4;</code>
     * @return The typeAction.
     */
    public com.katalon.kit.px.TypeAction getTypeAction() {
      if (typeActionBuilder_ == null) {
        if (actionOneofCase_ == 4) {
          return (com.katalon.kit.px.TypeAction) actionOneof_;
        }
        return com.katalon.kit.px.TypeAction.getDefaultInstance();
      } else {
        if (actionOneofCase_ == 4) {
          return typeActionBuilder_.getMessage();
        }
        return com.katalon.kit.px.TypeAction.getDefaultInstance();
      }
    }
    /**
     * <code>.px.TypeAction typeAction = 4;</code>
     */
    public Builder setTypeAction(com.katalon.kit.px.TypeAction value) {
      if (typeActionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        actionOneof_ = value;
        onChanged();
      } else {
        typeActionBuilder_.setMessage(value);
      }
      actionOneofCase_ = 4;
      return this;
    }
    /**
     * <code>.px.TypeAction typeAction = 4;</code>
     */
    public Builder setTypeAction(
        com.katalon.kit.px.TypeAction.Builder builderForValue) {
      if (typeActionBuilder_ == null) {
        actionOneof_ = builderForValue.build();
        onChanged();
      } else {
        typeActionBuilder_.setMessage(builderForValue.build());
      }
      actionOneofCase_ = 4;
      return this;
    }
    /**
     * <code>.px.TypeAction typeAction = 4;</code>
     */
    public Builder mergeTypeAction(com.katalon.kit.px.TypeAction value) {
      if (typeActionBuilder_ == null) {
        if (actionOneofCase_ == 4 &&
            actionOneof_ != com.katalon.kit.px.TypeAction.getDefaultInstance()) {
          actionOneof_ = com.katalon.kit.px.TypeAction.newBuilder((com.katalon.kit.px.TypeAction) actionOneof_)
              .mergeFrom(value).buildPartial();
        } else {
          actionOneof_ = value;
        }
        onChanged();
      } else {
        if (actionOneofCase_ == 4) {
          typeActionBuilder_.mergeFrom(value);
        }
        typeActionBuilder_.setMessage(value);
      }
      actionOneofCase_ = 4;
      return this;
    }
    /**
     * <code>.px.TypeAction typeAction = 4;</code>
     */
    public Builder clearTypeAction() {
      if (typeActionBuilder_ == null) {
        if (actionOneofCase_ == 4) {
          actionOneofCase_ = 0;
          actionOneof_ = null;
          onChanged();
        }
      } else {
        if (actionOneofCase_ == 4) {
          actionOneofCase_ = 0;
          actionOneof_ = null;
        }
        typeActionBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.px.TypeAction typeAction = 4;</code>
     */
    public com.katalon.kit.px.TypeAction.Builder getTypeActionBuilder() {
      return getTypeActionFieldBuilder().getBuilder();
    }
    /**
     * <code>.px.TypeAction typeAction = 4;</code>
     */
    public com.katalon.kit.px.TypeActionOrBuilder getTypeActionOrBuilder() {
      if ((actionOneofCase_ == 4) && (typeActionBuilder_ != null)) {
        return typeActionBuilder_.getMessageOrBuilder();
      } else {
        if (actionOneofCase_ == 4) {
          return (com.katalon.kit.px.TypeAction) actionOneof_;
        }
        return com.katalon.kit.px.TypeAction.getDefaultInstance();
      }
    }
    /**
     * <code>.px.TypeAction typeAction = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.katalon.kit.px.TypeAction, com.katalon.kit.px.TypeAction.Builder, com.katalon.kit.px.TypeActionOrBuilder> 
        getTypeActionFieldBuilder() {
      if (typeActionBuilder_ == null) {
        if (!(actionOneofCase_ == 4)) {
          actionOneof_ = com.katalon.kit.px.TypeAction.getDefaultInstance();
        }
        typeActionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.katalon.kit.px.TypeAction, com.katalon.kit.px.TypeAction.Builder, com.katalon.kit.px.TypeActionOrBuilder>(
                (com.katalon.kit.px.TypeAction) actionOneof_,
                getParentForChildren(),
                isClean());
        actionOneof_ = null;
      }
      actionOneofCase_ = 4;
      onChanged();;
      return typeActionBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.katalon.kit.px.SelectAction, com.katalon.kit.px.SelectAction.Builder, com.katalon.kit.px.SelectActionOrBuilder> selectActionBuilder_;
    /**
     * <code>.px.SelectAction selectAction = 5;</code>
     * @return Whether the selectAction field is set.
     */
    public boolean hasSelectAction() {
      return actionOneofCase_ == 5;
    }
    /**
     * <code>.px.SelectAction selectAction = 5;</code>
     * @return The selectAction.
     */
    public com.katalon.kit.px.SelectAction getSelectAction() {
      if (selectActionBuilder_ == null) {
        if (actionOneofCase_ == 5) {
          return (com.katalon.kit.px.SelectAction) actionOneof_;
        }
        return com.katalon.kit.px.SelectAction.getDefaultInstance();
      } else {
        if (actionOneofCase_ == 5) {
          return selectActionBuilder_.getMessage();
        }
        return com.katalon.kit.px.SelectAction.getDefaultInstance();
      }
    }
    /**
     * <code>.px.SelectAction selectAction = 5;</code>
     */
    public Builder setSelectAction(com.katalon.kit.px.SelectAction value) {
      if (selectActionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        actionOneof_ = value;
        onChanged();
      } else {
        selectActionBuilder_.setMessage(value);
      }
      actionOneofCase_ = 5;
      return this;
    }
    /**
     * <code>.px.SelectAction selectAction = 5;</code>
     */
    public Builder setSelectAction(
        com.katalon.kit.px.SelectAction.Builder builderForValue) {
      if (selectActionBuilder_ == null) {
        actionOneof_ = builderForValue.build();
        onChanged();
      } else {
        selectActionBuilder_.setMessage(builderForValue.build());
      }
      actionOneofCase_ = 5;
      return this;
    }
    /**
     * <code>.px.SelectAction selectAction = 5;</code>
     */
    public Builder mergeSelectAction(com.katalon.kit.px.SelectAction value) {
      if (selectActionBuilder_ == null) {
        if (actionOneofCase_ == 5 &&
            actionOneof_ != com.katalon.kit.px.SelectAction.getDefaultInstance()) {
          actionOneof_ = com.katalon.kit.px.SelectAction.newBuilder((com.katalon.kit.px.SelectAction) actionOneof_)
              .mergeFrom(value).buildPartial();
        } else {
          actionOneof_ = value;
        }
        onChanged();
      } else {
        if (actionOneofCase_ == 5) {
          selectActionBuilder_.mergeFrom(value);
        }
        selectActionBuilder_.setMessage(value);
      }
      actionOneofCase_ = 5;
      return this;
    }
    /**
     * <code>.px.SelectAction selectAction = 5;</code>
     */
    public Builder clearSelectAction() {
      if (selectActionBuilder_ == null) {
        if (actionOneofCase_ == 5) {
          actionOneofCase_ = 0;
          actionOneof_ = null;
          onChanged();
        }
      } else {
        if (actionOneofCase_ == 5) {
          actionOneofCase_ = 0;
          actionOneof_ = null;
        }
        selectActionBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.px.SelectAction selectAction = 5;</code>
     */
    public com.katalon.kit.px.SelectAction.Builder getSelectActionBuilder() {
      return getSelectActionFieldBuilder().getBuilder();
    }
    /**
     * <code>.px.SelectAction selectAction = 5;</code>
     */
    public com.katalon.kit.px.SelectActionOrBuilder getSelectActionOrBuilder() {
      if ((actionOneofCase_ == 5) && (selectActionBuilder_ != null)) {
        return selectActionBuilder_.getMessageOrBuilder();
      } else {
        if (actionOneofCase_ == 5) {
          return (com.katalon.kit.px.SelectAction) actionOneof_;
        }
        return com.katalon.kit.px.SelectAction.getDefaultInstance();
      }
    }
    /**
     * <code>.px.SelectAction selectAction = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.katalon.kit.px.SelectAction, com.katalon.kit.px.SelectAction.Builder, com.katalon.kit.px.SelectActionOrBuilder> 
        getSelectActionFieldBuilder() {
      if (selectActionBuilder_ == null) {
        if (!(actionOneofCase_ == 5)) {
          actionOneof_ = com.katalon.kit.px.SelectAction.getDefaultInstance();
        }
        selectActionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.katalon.kit.px.SelectAction, com.katalon.kit.px.SelectAction.Builder, com.katalon.kit.px.SelectActionOrBuilder>(
                (com.katalon.kit.px.SelectAction) actionOneof_,
                getParentForChildren(),
                isClean());
        actionOneof_ = null;
      }
      actionOneofCase_ = 5;
      onChanged();;
      return selectActionBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.katalon.kit.px.GetInnerTextAction, com.katalon.kit.px.GetInnerTextAction.Builder, com.katalon.kit.px.GetInnerTextActionOrBuilder> getInnerTextActionBuilder_;
    /**
     * <code>.px.GetInnerTextAction getInnerTextAction = 6;</code>
     * @return Whether the getInnerTextAction field is set.
     */
    public boolean hasGetInnerTextAction() {
      return actionOneofCase_ == 6;
    }
    /**
     * <code>.px.GetInnerTextAction getInnerTextAction = 6;</code>
     * @return The getInnerTextAction.
     */
    public com.katalon.kit.px.GetInnerTextAction getGetInnerTextAction() {
      if (getInnerTextActionBuilder_ == null) {
        if (actionOneofCase_ == 6) {
          return (com.katalon.kit.px.GetInnerTextAction) actionOneof_;
        }
        return com.katalon.kit.px.GetInnerTextAction.getDefaultInstance();
      } else {
        if (actionOneofCase_ == 6) {
          return getInnerTextActionBuilder_.getMessage();
        }
        return com.katalon.kit.px.GetInnerTextAction.getDefaultInstance();
      }
    }
    /**
     * <code>.px.GetInnerTextAction getInnerTextAction = 6;</code>
     */
    public Builder setGetInnerTextAction(com.katalon.kit.px.GetInnerTextAction value) {
      if (getInnerTextActionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        actionOneof_ = value;
        onChanged();
      } else {
        getInnerTextActionBuilder_.setMessage(value);
      }
      actionOneofCase_ = 6;
      return this;
    }
    /**
     * <code>.px.GetInnerTextAction getInnerTextAction = 6;</code>
     */
    public Builder setGetInnerTextAction(
        com.katalon.kit.px.GetInnerTextAction.Builder builderForValue) {
      if (getInnerTextActionBuilder_ == null) {
        actionOneof_ = builderForValue.build();
        onChanged();
      } else {
        getInnerTextActionBuilder_.setMessage(builderForValue.build());
      }
      actionOneofCase_ = 6;
      return this;
    }
    /**
     * <code>.px.GetInnerTextAction getInnerTextAction = 6;</code>
     */
    public Builder mergeGetInnerTextAction(com.katalon.kit.px.GetInnerTextAction value) {
      if (getInnerTextActionBuilder_ == null) {
        if (actionOneofCase_ == 6 &&
            actionOneof_ != com.katalon.kit.px.GetInnerTextAction.getDefaultInstance()) {
          actionOneof_ = com.katalon.kit.px.GetInnerTextAction.newBuilder((com.katalon.kit.px.GetInnerTextAction) actionOneof_)
              .mergeFrom(value).buildPartial();
        } else {
          actionOneof_ = value;
        }
        onChanged();
      } else {
        if (actionOneofCase_ == 6) {
          getInnerTextActionBuilder_.mergeFrom(value);
        }
        getInnerTextActionBuilder_.setMessage(value);
      }
      actionOneofCase_ = 6;
      return this;
    }
    /**
     * <code>.px.GetInnerTextAction getInnerTextAction = 6;</code>
     */
    public Builder clearGetInnerTextAction() {
      if (getInnerTextActionBuilder_ == null) {
        if (actionOneofCase_ == 6) {
          actionOneofCase_ = 0;
          actionOneof_ = null;
          onChanged();
        }
      } else {
        if (actionOneofCase_ == 6) {
          actionOneofCase_ = 0;
          actionOneof_ = null;
        }
        getInnerTextActionBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.px.GetInnerTextAction getInnerTextAction = 6;</code>
     */
    public com.katalon.kit.px.GetInnerTextAction.Builder getGetInnerTextActionBuilder() {
      return getGetInnerTextActionFieldBuilder().getBuilder();
    }
    /**
     * <code>.px.GetInnerTextAction getInnerTextAction = 6;</code>
     */
    public com.katalon.kit.px.GetInnerTextActionOrBuilder getGetInnerTextActionOrBuilder() {
      if ((actionOneofCase_ == 6) && (getInnerTextActionBuilder_ != null)) {
        return getInnerTextActionBuilder_.getMessageOrBuilder();
      } else {
        if (actionOneofCase_ == 6) {
          return (com.katalon.kit.px.GetInnerTextAction) actionOneof_;
        }
        return com.katalon.kit.px.GetInnerTextAction.getDefaultInstance();
      }
    }
    /**
     * <code>.px.GetInnerTextAction getInnerTextAction = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.katalon.kit.px.GetInnerTextAction, com.katalon.kit.px.GetInnerTextAction.Builder, com.katalon.kit.px.GetInnerTextActionOrBuilder> 
        getGetInnerTextActionFieldBuilder() {
      if (getInnerTextActionBuilder_ == null) {
        if (!(actionOneofCase_ == 6)) {
          actionOneof_ = com.katalon.kit.px.GetInnerTextAction.getDefaultInstance();
        }
        getInnerTextActionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.katalon.kit.px.GetInnerTextAction, com.katalon.kit.px.GetInnerTextAction.Builder, com.katalon.kit.px.GetInnerTextActionOrBuilder>(
                (com.katalon.kit.px.GetInnerTextAction) actionOneof_,
                getParentForChildren(),
                isClean());
        actionOneof_ = null;
      }
      actionOneofCase_ = 6;
      onChanged();;
      return getInnerTextActionBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:px.Action)
  }

  // @@protoc_insertion_point(class_scope:px.Action)
  private static final com.katalon.kit.px.Action DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.katalon.kit.px.Action();
  }

  public static com.katalon.kit.px.Action getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Action>
      PARSER = new com.google.protobuf.AbstractParser<Action>() {
    @java.lang.Override
    public Action parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Action(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Action> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Action> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.katalon.kit.px.Action getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

