// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/px.proto

package com.katalon.kit.px;

public interface ActionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:px.Action)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.px.LaunchAction launchAction = 1;</code>
   * @return Whether the launchAction field is set.
   */
  boolean hasLaunchAction();
  /**
   * <code>.px.LaunchAction launchAction = 1;</code>
   * @return The launchAction.
   */
  com.katalon.kit.px.LaunchAction getLaunchAction();
  /**
   * <code>.px.LaunchAction launchAction = 1;</code>
   */
  com.katalon.kit.px.LaunchActionOrBuilder getLaunchActionOrBuilder();

  /**
   * <code>.px.GotoAction gotoAction = 2;</code>
   * @return Whether the gotoAction field is set.
   */
  boolean hasGotoAction();
  /**
   * <code>.px.GotoAction gotoAction = 2;</code>
   * @return The gotoAction.
   */
  com.katalon.kit.px.GotoAction getGotoAction();
  /**
   * <code>.px.GotoAction gotoAction = 2;</code>
   */
  com.katalon.kit.px.GotoActionOrBuilder getGotoActionOrBuilder();

  /**
   * <code>.px.ClickAction clickAction = 3;</code>
   * @return Whether the clickAction field is set.
   */
  boolean hasClickAction();
  /**
   * <code>.px.ClickAction clickAction = 3;</code>
   * @return The clickAction.
   */
  com.katalon.kit.px.ClickAction getClickAction();
  /**
   * <code>.px.ClickAction clickAction = 3;</code>
   */
  com.katalon.kit.px.ClickActionOrBuilder getClickActionOrBuilder();

  /**
   * <code>.px.TypeAction typeAction = 4;</code>
   * @return Whether the typeAction field is set.
   */
  boolean hasTypeAction();
  /**
   * <code>.px.TypeAction typeAction = 4;</code>
   * @return The typeAction.
   */
  com.katalon.kit.px.TypeAction getTypeAction();
  /**
   * <code>.px.TypeAction typeAction = 4;</code>
   */
  com.katalon.kit.px.TypeActionOrBuilder getTypeActionOrBuilder();

  /**
   * <code>.px.SelectAction selectAction = 5;</code>
   * @return Whether the selectAction field is set.
   */
  boolean hasSelectAction();
  /**
   * <code>.px.SelectAction selectAction = 5;</code>
   * @return The selectAction.
   */
  com.katalon.kit.px.SelectAction getSelectAction();
  /**
   * <code>.px.SelectAction selectAction = 5;</code>
   */
  com.katalon.kit.px.SelectActionOrBuilder getSelectActionOrBuilder();

  /**
   * <code>.px.GetInnerTextAction getInnerTextAction = 6;</code>
   * @return Whether the getInnerTextAction field is set.
   */
  boolean hasGetInnerTextAction();
  /**
   * <code>.px.GetInnerTextAction getInnerTextAction = 6;</code>
   * @return The getInnerTextAction.
   */
  com.katalon.kit.px.GetInnerTextAction getGetInnerTextAction();
  /**
   * <code>.px.GetInnerTextAction getInnerTextAction = 6;</code>
   */
  com.katalon.kit.px.GetInnerTextActionOrBuilder getGetInnerTextActionOrBuilder();

  public com.katalon.kit.px.Action.ActionOneofCase getActionOneofCase();
}
