// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/px.proto

package com.katalon.kit.px;

public final class BrowserProto {
  private BrowserProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_px_DoResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_px_DoResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_px_DoRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_px_DoRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_px_Action_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_px_Action_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_px_LaunchAction_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_px_LaunchAction_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_px_GotoAction_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_px_GotoAction_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_px_ClickAction_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_px_ClickAction_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_px_TypeAction_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_px_TypeAction_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_px_SelectAction_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_px_SelectAction_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_px_GetInnerTextAction_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_px_GetInnerTextAction_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016proto/px.proto\022\002px\"\034\n\nDoResponse\022\016\n\006re" +
      "sult\030\001 \001(\t\"(\n\tDoRequest\022\033\n\007actions\030\001 \003(\013" +
      "2\n.px.Action\"\226\002\n\006Action\022(\n\014launchAction\030" +
      "\001 \001(\0132\020.px.LaunchActionH\000\022$\n\ngotoAction\030" +
      "\002 \001(\0132\016.px.GotoActionH\000\022&\n\013clickAction\030\003" +
      " \001(\0132\017.px.ClickActionH\000\022$\n\ntypeAction\030\004 " +
      "\001(\0132\016.px.TypeActionH\000\022(\n\014selectAction\030\005 " +
      "\001(\0132\020.px.SelectActionH\000\0224\n\022getInnerTextA" +
      "ction\030\006 \001(\0132\026.px.GetInnerTextActionH\000B\016\n" +
      "\014action_oneof\" \n\014LaunchAction\022\020\n\010headles" +
      "s\030\001 \001(\010\"\031\n\nGotoAction\022\013\n\003url\030\001 \001(\t\"\037\n\013Cl" +
      "ickAction\022\020\n\010selector\030\001 \001(\t\",\n\nTypeActio" +
      "n\022\020\n\010selector\030\001 \001(\t\022\014\n\004text\030\002 \001(\t\"0\n\014Sel" +
      "ectAction\022\020\n\010selector\030\001 \001(\t\022\016\n\006values\030\002 " +
      "\003(\t\"&\n\022GetInnerTextAction\022\020\n\010selector\030\001 " +
      "\001(\t20\n\007Browser\022%\n\002Do\022\r.px.DoRequest\032\016.px" +
      ".DoResponse\"\000B$\n\022com.katalon.kit.pxB\014Bro" +
      "wserProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_px_DoResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_px_DoResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_px_DoResponse_descriptor,
        new java.lang.String[] { "Result", });
    internal_static_px_DoRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_px_DoRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_px_DoRequest_descriptor,
        new java.lang.String[] { "Actions", });
    internal_static_px_Action_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_px_Action_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_px_Action_descriptor,
        new java.lang.String[] { "LaunchAction", "GotoAction", "ClickAction", "TypeAction", "SelectAction", "GetInnerTextAction", "ActionOneof", });
    internal_static_px_LaunchAction_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_px_LaunchAction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_px_LaunchAction_descriptor,
        new java.lang.String[] { "Headless", });
    internal_static_px_GotoAction_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_px_GotoAction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_px_GotoAction_descriptor,
        new java.lang.String[] { "Url", });
    internal_static_px_ClickAction_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_px_ClickAction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_px_ClickAction_descriptor,
        new java.lang.String[] { "Selector", });
    internal_static_px_TypeAction_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_px_TypeAction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_px_TypeAction_descriptor,
        new java.lang.String[] { "Selector", "Text", });
    internal_static_px_SelectAction_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_px_SelectAction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_px_SelectAction_descriptor,
        new java.lang.String[] { "Selector", "Values", });
    internal_static_px_GetInnerTextAction_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_px_GetInnerTextAction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_px_GetInnerTextAction_descriptor,
        new java.lang.String[] { "Selector", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
