// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/px.proto

package com.katalon.kit.px;

public interface DoRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:px.DoRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .px.Action actions = 1;</code>
   */
  java.util.List<com.katalon.kit.px.Action> 
      getActionsList();
  /**
   * <code>repeated .px.Action actions = 1;</code>
   */
  com.katalon.kit.px.Action getActions(int index);
  /**
   * <code>repeated .px.Action actions = 1;</code>
   */
  int getActionsCount();
  /**
   * <code>repeated .px.Action actions = 1;</code>
   */
  java.util.List<? extends com.katalon.kit.px.ActionOrBuilder> 
      getActionsOrBuilderList();
  /**
   * <code>repeated .px.Action actions = 1;</code>
   */
  com.katalon.kit.px.ActionOrBuilder getActionsOrBuilder(
      int index);
}
