// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/px.proto

package com.katalon.kit.px;

public interface GetInnerTextActionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:px.GetInnerTextAction)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string selector = 1;</code>
   * @return The selector.
   */
  java.lang.String getSelector();
  /**
   * <code>string selector = 1;</code>
   * @return The bytes for selector.
   */
  com.google.protobuf.ByteString
      getSelectorBytes();
}
