// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/px.proto

package com.katalon.kit.px;

public interface GotoActionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:px.GotoAction)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * https://www.google.com
   * </pre>
   *
   * <code>string url = 1;</code>
   * @return The url.
   */
  java.lang.String getUrl();
  /**
   * <pre>
   * https://www.google.com
   * </pre>
   *
   * <code>string url = 1;</code>
   * @return The bytes for url.
   */
  com.google.protobuf.ByteString
      getUrlBytes();
}
