// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/px.proto

package com.katalon.kit.px;

public interface LaunchActionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:px.LaunchAction)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool headless = 1;</code>
   * @return The headless.
   */
  boolean getHeadless();
}
