name: Package PX Server

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [linux-latest]
        node-version: [10.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache
        uses: actions/cache@v1.0.3
        with:
          path: node_modules
          key: ${{ runner.os }}-node${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}

      - name: Install packages and build with Node.js ${{ matrix.node-version }}
        env:
          CI: true
        run: |
          npm install
          npm run build
          echo "::set-env name=BUILD_VERSION::$(node -p "require('./package').version")"

      - name: Draft new release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run release

      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        if: success()
        with:
          name: px-server-${{ runner.os }}-${{ env.BUILD_VERSION }}
          path: dist