name: Package PX Server

on:
  push:
    branches:
      - master
#  pull_request:
#    branches:
#      - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version:
          - 10.x

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache
        uses: actions/cache@v1.0.3
        with:
          path: node_modules
          key: ${{ runner.os }}-node${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}

      - name: Install packages and build with Node.js ${{ matrix.node-version }}
        env:
          CI: true
        run: |
          npm install
          npm run build
          echo "::set-env name=BUILD_VERSION::$(node -p "require('./package').version")"

      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        if: success()
        with:
          name: px-server-${{ env.BUILD_VERSION }}
          path: dist

#      - name: Draft new release
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        run: npm run release