name: Publish to PyPI

on: 
  push:
    branches:
      - release  

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Install dependencies
      working-directory: ./python
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run codegen
      working-directory: ./python
      run: |
        python run_codegen.py

    - name: Generating distribution archives
      working-directory: ./python
      run: |
        pip install --upgrade setuptools wheel
        python setup.py sdist

    - name: Publish distribution to PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        user: __token__
        password: ${{ secrets.pypi_password }}
        packages_dir: python/dist/
